### ISSUE TITLE
implement with other other camera view

### ISSUE THREAD

**Issue by RahulGupta2312** [Fotoapparat/FaceDetector#26]
How can I integrate with any other third party camera view?

**Comment by dmitry-zaitsev** [comment]
You can create and call `FaceDetector` class directly.

**Comment by RahulGupta2312** [comment]
I got this issue while implementing with this cameraview https://github.com/natario1/CameraView. 

    java.lang.IllegalStateException: Can't find CameraView
                                                                     at io.fotoapparat.facedetector.view.CameraOverlayLayout.findCameraView(CameraOverlayLayout.java:66)
                                                                     at io.fotoapparat.facedetector.view.CameraOverlayLayout.onLayout(CameraOverlayLayout.java:35)
                                                                     at android.view.View.layout(View.java:16975)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
                                                                     at android.view.View.layout(View.java:16975)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
                                                                     at android.view.View.layout(View.java:16975)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
                                                                     at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1990)
                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1755)
                                                                     at android.view.View.layout(View.java:16975)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
                                                                     at android.view.View.layout(View.java:16975)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
                                                                     at android.view.View.layout(View.java:16975)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
                                                                     at android.view.View.layout(View.java:16975)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
                                                                     at android.view.View.layout(View.java:16975)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
                                                                     at android.view.View.layout(View.java:16975)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
                                                                     at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2755)
                                                                     at android.view.View.layout(View.java:16975)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                                     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2552)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2255)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1321)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6737)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:696)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
                                                                     at android.os.Handler.handleCallback(Handler.java:815)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                     at android.os.Looper.loop(Looper.java:207)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5776)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)



The xml is as follows:
 <io.fotoapparat.facedetector.view.CameraOverlayLayout
                        android:layout_width="match_parent"
                        android:layout_height="match_parent">

                        <com.otaliastudios.cameraview.CameraView
                            android:id="@+id/cameraView"
                            android:layout_width="match_parent"
                            android:layout_height="match_parent"
                            app:cameraAudio="on"
                            app:cameraFacing="front"
                            app:cameraSessionType="video"
                            app:cameraVideoQuality="max480p" />

                        <io.fotoapparat.facedetector.view.RectanglesView
                            android:layout_width="match_parent"
                            android:layout_height="match_parent" />
                    </io.fotoapparat.facedetector.view.CameraOverlayLayout>

and, adding face detector like this, 
 cameraView.addFrameProcessor(frame -> FaceDetector.create(context).detectFaces(frame.getData(), 100, 100, 0));

**Comment by dmitry-zaitsev** [comment]
`CameraOverlayLayout` will not work without the `Fotoapparat`. That is something you would have to implement yourself.
